services:
  feedbackservice:
    image: "joydipdocker/feedback-image:1.0.0"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - PASSWORD=Joydip@123
    volumes:
      # named volume
      - feedback-volume:/app/feedback
      # anonymous volume
      - /app/node_modules
      # bind mount
      - ./pages:/app/pages
    tmpfs:
      - /app/temp
    ports:
      - "3001:3000"
      - "3002:3000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  feedback-volume:
