apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-first
spec:
  replicas: 2
  selector:
    matchLabels:
      apptype: backend-pod
  template:
    metadata:
      name: kub-first-pod
      labels:
        apptype: backend-pod
    spec:
      containers:
        - name: kube-first-container
          image: joydipdocker/kub-first:2.0.0
          # imagePullPolicy: Always
          # env:
          #   - name: PORT
          #     value: "3000"
          env:
            - name: PORT 
              valueFrom:
                configMapKeyRef:
                  name: key-value-pairs
                  key: portno
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
        
              