apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: "500Mi"
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce #only one worker node can use this
    # - ReadOnlyMany # multiple pods dfrom multiple worker nodes
    # - ReadWriteMany # multiple pods from multiple worker nodes
    # - ReadWriteOncePod # single pod
  hostPath:
    path: /storydata
    type: DirectoryOrCreate